export const WEBSITE_NAME: string = "CoLoop"
export const MARKETING_BASE_URL: string = "https://coloop.ai"
export const APP_BASE_URL: string = "https://app.coloop.ai"
export const DOMAIN: string = "coloop.ai"
export const APP_DOMAIN: string = "app.coloop.ai"
export const SUPPORT_EMAIL: string = "support@coloop.ai"
export const DOCS_URL: string = "https://docs.coloop.ai"

export const WebsiteDescription: string = "Ai Research for Insights Teams."
export const LOGO: string = "/logo.png"
